# Generated by Django 6.0.1 on 2026-01-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image_alter_auditlog_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
